version: "3.3"
services:
  backend:
    image: fergalmoran/xtreamium-backend
    container_name: "xtreamium-backend"
    environment:
      - TZ=Europe/Dublin
    networks:
      - "traefik_proxy"
    restart: always
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.xtreamium-backend.rule=Host(`api.streams.fergl.ie`)"
      - "traefik.http.routers.xtreamium-backend.entrypoints=websecure"
      - "traefik.http.routers.xtreamium-backend.tls.certresolver=noodles-resolver"
      - "traefik.http.services.xtreamium-backend.loadbalancer.server.port=80"
  frontend:
    image: fergalmoran/xtreamium-frontend
    container_name: "xtreamium-frontend"
    environment:
      - TZ=Europe/Dublin
    networks:
      - "traefik_proxy"
    restart: always
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.xtreamium-frontend.rule=Host(`streams.fergl.ie`)"
      - "traefik.http.routers.xtreamium-frontend.entrypoints=websecure"
      - "traefik.http.routers.xtreamium-frontend.tls.certresolver=noodles-resolver"
      - "traefik.http.services.xtreamium-frontend.loadbalancer.server.port=80"

networks:
  traefik_proxy:
    external: true
    name: traefik_proxy
